server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx
    username: root
    password: 123456
  # Redis的相关配置
  data:
    redis:
      host: localhost
      port: 6379

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 自定义配置
spzx:
  auth:
    excludePaths:
      - /admin/user/login
      - /admin/user/validateCode
      - /admin/user/logout
  minio:
    endpointUrl: http://127.0.0.1:9000
    accessKey: sakura
    secretKey: 20011123xwj
    bucketName: spzx-bucket
